#!/usr/bin/env python3
"""Generate ``ingest/cluster_seed.sql`` from the Matter ZCL data model.

The cluster and attribute registry in the database is derived from the
authoritative definitions published in the connectedhomeip repository:

    https://github.com/project-chip/connectedhomeip
    src/app/zap-templates/zcl/data-model/chip/*.xml

Each XML file describes one (or more) standard clusters, their code and their
server-side attributes. This script downloads them, de-duplicates by cluster /
attribute code and writes idempotent SQL (TRUNCATE + INSERT) for the
``matter_clusters`` and ``matter_cluster_attributes`` tables.

Run from the repository root::

    python ingest/tools/generate_cluster_seed.py

The generated file is committed so the runtime does not need network access.
Re-run this script after a Matter release to refresh the registry.
"""

from __future__ import annotations

import json
import sys
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

API = (
    "https://api.github.com/repos/project-chip/connectedhomeip/contents/"
    "src/app/zap-templates/zcl/data-model/chip"
)
RAW = (
    "https://raw.githubusercontent.com/project-chip/connectedhomeip/master/"
    "src/app/zap-templates/zcl/data-model/chip/"
)
OUT = Path(__file__).resolve().parent.parent / "cluster_seed.sql"

# Rows per INSERT statement (keeps individual statements a sane size).
CHUNK = 200


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "hamoti-cluster-seed"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read()


def sql_str(value) -> str:
    return "'" + str(value).replace("'", "''") + "'"


def parse_code(value: str | None) -> int | None:
    if value is None:
        return None
    value = value.strip()
    if not value:
        return None
    try:
        return int(value, 0)
    except ValueError:
        return None


def chunks(seq, size):
    for i in range(0, len(seq), size):
        yield seq[i : i + size]


def main() -> None:
    listing = json.loads(fetch(API))
    files = sorted(f["name"] for f in listing if f["name"].endswith(".xml"))

    # code -> {"name": str, "category": str, "attrs": {code: tuple}}
    clusters: dict[int, dict] = {}

    for filename in files:
        try:
            root = ET.fromstring(fetch(RAW + filename))
        except Exception as exc:  # noqa: BLE001 - report and continue
            print(f"-- WARN {filename}: {exc}", file=sys.stderr)
            continue

        for cluster in root.iter("cluster"):
            code = parse_code(cluster.findtext("code"))
            if code is None:
                continue
            # Standard clusters live in 0x0000-0x7FFF; anything above is
            # reserved, manufacturer-specific (0xFC00+) or SDK test data.
            if not 0 < code <= 0x7FFF:
                continue
            name = (cluster.findtext("name") or "").strip()
            category = (cluster.findtext("domain") or "").strip()
            entry = clusters.setdefault(
                code, {"name": "", "category": "", "attrs": {}}
            )
            if name:
                entry["name"] = name
            if category:
                entry["category"] = category

            for attr in cluster.findall("attribute"):
                attr_code = parse_code(attr.get("code"))
                attr_name = attr.get("name")
                if attr_code is None or not attr_name:
                    continue
                if attr.get("side") not in ("server", "either"):
                    continue
                entry["attrs"][attr_code] = (
                    attr_code,
                    attr_name,
                    attr.get("type") or "",
                    attr.get("optional") == "true",
                    attr.get("isNullable") == "true",
                )

    named = {code: e for code, e in clusters.items() if e["name"]}
    if not named:
        raise SystemExit("no clusters parsed - refusing to write an empty seed")

    lines: list[str] = []
    lines.append("-- Generated by ingest/tools/generate_cluster_seed.py -- DO NOT EDIT.")
    lines.append("-- Source: project-chip/connectedhomeip ZCL data model (standard clusters).")
    lines.append("-- Re-run the generator after a Matter release to refresh this registry.")
    lines.append("")
    lines.append("TRUNCATE TABLE matter_cluster_attributes;")
    lines.append("TRUNCATE TABLE matter_clusters;")
    lines.append("")

    cluster_rows = [
        (code, e["name"], e["category"]) for code, e in sorted(named.items())
    ]
    for chunk in chunks(cluster_rows, CHUNK):
        values = ",\n    ".join(
            f"({code}, {sql_str(name)}, {sql_str(category)})"
            for code, name, category in chunk
        )
        lines.append(
            "INSERT INTO matter_clusters (cluster_id, name, category) VALUES\n"
            f"    {values};"
        )
    lines.append("")

    attr_rows = [
        (code, a[0], a[1], a[2], a[3], a[4])
        for code, e in sorted(named.items())
        for a in sorted(e["attrs"].values())
    ]
    for chunk in chunks(attr_rows, CHUNK):
        values = ",\n    ".join(
            f"({cid}, {aid}, {sql_str(name)}, {sql_str(atype)}, "
            f"{'true' if optional else 'false'}, {'true' if nullable else 'false'})"
            for cid, aid, name, atype, optional, nullable in chunk
        )
        lines.append(
            "INSERT INTO matter_cluster_attributes "
            "(cluster_id, attribute_id, name, type, is_optional, is_nullable) VALUES\n"
            f"    {values};"
        )

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"wrote {OUT}: {len(cluster_rows)} clusters, {len(attr_rows)} attributes",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
